names:
- ball
- goalkeeper
- player
- referee
roboflow:
  license: CC BY 4.0
  project: football-players-detection-3zvbc
  url: https://universe.roboflow.com/roboflow-jvuqo/football-players-detection-3zvbc/dataset/12
  version: 12
  workspace: roboflow-jvuqo
test: test
train: train
path: data/football-players-detection-3zvbc
validation: valid
class_num: 4
